version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - "$PWD/docker/.data/db:/var/lib/mysql"
      - "$PWD/docker/initial-schema.sql:/docker-entrypoint-initdb.d/dump.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Uw*tm8?
      MYSQL_USER: webdbuser
      MYSQL_PASSWORD: Abc123
      MYSQL_DATABASE: webdb
  web:
    image: malitta/php
    restart: always
    volumes:
      - "$PWD:/var/www/html"
